id = 12
kind = "bug"
title = "Active node tree lines should also be highlighted"
description = ""
author = "Thomas Mathews <thomas.c.mathews@gmail.com>"
state = "open"
created_at = "2026-07-17T21:55:16.519261207Z"
updated_at = "2026-07-17T21:55:16.523501692Z"
