id = 13
kind = "bug"
title = "Empty nodes should state so with label"
description = ""
author = "Thomas Mathews <thomas.c.mathews@gmail.com>"
state = "open"
created_at = "2026-07-17T21:55:56.486609954Z"
updated_at = "2026-07-17T21:55:56.490781529Z"
