id = 19
kind = "bug"
title = 'App starts with "no selection" in the URL bar'
description = "Since there is always a node open, we should default that to the active node. Thus the URL bar should always have a value."
author = "Thomas Mathews <thomas.c.mathews@gmail.com>"
state = "open"
created_at = "2026-07-18T00:04:01.583208430Z"
updated_at = "2026-07-18T00:05:57.019071369Z"
