id = 4
kind = "todo"
title = "Draw curved lines to nodes"
description = ""
author = "Thomas Mathews <thomas.c.mathews@gmail.com>"
state = "open"
created_at = "2026-07-17T21:47:37.161153673Z"
updated_at = "2026-07-17T21:47:41.234380161Z"
