id = 5
kind = "todo"
title = "Add basic support for copy, paste, move, rename"
description = ""
author = "Thomas Mathews <thomas.c.mathews@gmail.com>"
state = "open"
created_at = "2026-07-17T21:47:57.343232947Z"
updated_at = "2026-07-17T21:47:57.773176985Z"
