id = 6
kind = "todo"
title = "View file permissions & metadata"
description = ""
author = "Thomas Mathews <thomas.c.mathews@gmail.com>"
state = "open"
created_at = "2026-07-17T21:48:12.115931266Z"
updated_at = "2026-07-17T21:48:13.193935056Z"
