id = 7
kind = "todo"
title = "Right click menu to access file operations"
description = ""
author = "Thomas Mathews <thomas.c.mathews@gmail.com>"
state = "closed"
resolution = "fixed"
created_at = "2026-07-17T21:48:41.040238487Z"
updated_at = "2026-07-18T18:33:10.070661838Z"
